using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Sand : MonoBehaviour
{
    [Header("ㄆン菏钮")]
    public VoidEventSO afterSceneLoadEvent;

    [Header("à獍鸭")]
    private bool isExploded = false; // 兢瞀hΩ牟oP反
    private SandAnimation sandAnimation;

    private void OnEnable()
    {
        afterSceneLoadEvent.onEventRaised += onAfterSceneLoadEvent;
    }

    private void OnDisable()
    {
        afterSceneLoadEvent.onEventRaised -= onAfterSceneLoadEvent;
    }

    private void onAfterSceneLoadEvent()
    {
        Destroy(this.gameObject);
    }

    private void Awake()
    {
        sandAnimation = transform.Find("Ani").GetComponent<SandAnimation>();
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (!isExploded) // TO度牟o@Ω
        {
            isExploded = true;
            sandAnimation.sandexplode();
        }
    }
}
    

